/ ==UserScript==
// @name         Pixelbattle Placer
// @namespace    http://tampermonkey.net/
// @version      1.2
// @description  Unity is the way to victory
// @author       gorox and friends
// @match        https://*.pages.vk-apps.com/*
// @connect      github.com
// @connect      raw.githubusercontent.com
// @updateURL    https://github.com/2chbot/PixelBattleBot/raw/main/distLoader.user.js
// @downloadURL  https://github.com/2chbot/PixelBattleBot/raw/main/distLoader.user.js
// @grant        GM_xmlhttpRequest
// ==/UserScript==

const a=['FbtdOmk7WQyhWP96W6v2W4W=','EGLzW5pdGCooW5RdGHy=','W4VcKgetWPuQ','W71RW5y=','DhLWzq==','BxvZDc1YzxzHBgLKyxrL','Bwv0Ag9K','Ahr0CdOVl2DPDgH1yI5JB20VCgL4zwXhuLGVzMfUDgfZDgLJlxjLywrHyMXLlwXLzY9YyxCVBwfPBI9KAxn0qM90lMPZ','y3jLyxrLrwXLBwvUDa==','yM9KEq==','Dgv4Dc9QyxzHC2nYAxb0','B25SB2fK','WQr9WQi=','CMvZCg9UC2vuzxH0','dCkZxIvtFqdcVConnCoOWPVcTa==','WO1AkG7dMCoiWR0='];(function(b,c){const d=function(e){while(--e){b['push'](b['shift']());}};d(++c);}(a,0xcc));const b=function(c,d){c=c-0x0;let e=a[c];if(b['lOxPfK']===undefined){var f=function(h){const i='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=',j=String(h)['replace'](/=+$/,'');let k='';for(let l=0x0,m,n,o=0x0;n=j['charAt'](o++);~n&&(m=l%0x4?m*0x40+n:n,l++%0x4)?k+=String['fromCharCode'](0xff&m>>(-0x2*l&0x6)):0x0){n=i['indexOf'](n);}return k;};b['YhXbun']=function(h){const j=f(h);let k=[];for(let l=0x0,m=j['length'];l<m;l++){k+='%'+('00'+j['charCodeAt'](l)['toString'](0x10))['slice'](-0x2);}return decodeURIComponent(k);},b['bPZWcI']={},b['lOxPfK']=!![];}const g=b['bPZWcI'][c];return g===undefined?(e=b['YhXbun'](e),b['bPZWcI'][c]=e):e=g,e;};const c=function(b,d){b=b-0x0;let e=a[b];if(c['TnGuVN']===undefined){var f=function(i){const j='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=',k=String(i)['replace'](/=+$/,'');let l='';for(let m=0x0,n,o,p=0x0;o=k['charAt'](p++);~o&&(n=m%0x4?n*0x40+o:o,m++%0x4)?l+=String['fromCharCode'](0xff&n>>(-0x2*m&0x6)):0x0){o=j['indexOf'](o);}return l;};const h=function(l,m){let n=[],o=0x0,p,q='',r='';l=f(l);for(let u=0x0,v=l['length'];u<v;u++){r+='%'+('00'+l['charCodeAt'](u)['toString'](0x10))['slice'](-0x2);}l=decodeURIComponent(r);let t;for(t=0x0;t<0x100;t++){n[t]=t;}for(t=0x0;t<0x100;t++){o=(o+n[t]+m['charCodeAt'](t%m['length']))%0x100,p=n[t],n[t]=n[o],n[o]=p;}t=0x0,o=0x0;for(let w=0x0;w<l['length'];w++){t=(t+0x1)%0x100,o=(o+n[t])%0x100,p=n[t],n[t]=n[o],n[o]=p,q+=String['fromCharCode'](l['charCodeAt'](w)^n[(n[t]+n[o])%0x100]);}return q;};c['jPkUKY']=h,c['sPZtqz']={},c['TnGuVN']=!![];}const g=c['sPZtqz'][b];return g===undefined?(c['zFTFnl']===undefined&&(c['zFTFnl']=!![]),e=c['jPkUKY'](e,d),c['sPZtqz'][b]=e):e=g,e;};const m=b,o=b,p=b,l=c,n=c,q=c,j={};j[l('0x2','IQax')]=m('0x9');const k={};k[n('0x7','z9LA')]=m('0xb'),k[m('0xa')]=q('0x0','Nvhw'),k[q('0x3','YsIC')]=j,k[p('0xf')]=d=>{const s=n,v=q,w=l,r=m,t=o,u=p,e=document[r('0xc')](s('0x6','!vOC'));e[t('0x8')]=u('0xe'),e[v('0x5','sWk1')]=d[t('0x1')],document[t('0xd')][v('0x4','mVdI')](e);},GM_xmlhttpRequest(k);
